version: '3.8'

services:
  mermer-db:
    image: postgres:18-alpine
    container_name: mermer-postgres-18
    restart: always
    environment:
      POSTGRES_DB: mermer_db
      POSTGRES_USER: mermer_app
      POSTGRES_PASSWORD: ChuliyevSecurePassword2026!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Mermer.Data.Postgres/Scripts/001_create_database.sql:/docker-entrypoint-initdb.d/001_create_database.sql

  mermer-api:
    container_name: mermer-api
    build:
      context: .
      dockerfile: Mermer.Api/Dockerfile
    restart: always
    ports:
      - "5050:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Postgres=Host=mermer-db;Database=mermer_db;Username=mermer_app;Password=ChuliyevSecurePassword2026!
    depends_on:
      - mermer-db

volumes:
  postgres_data: