<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWpf>true</UseWpf>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationIcon>binyat_icon_003_d85_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mermer.Base\Mermer.csproj" />
    <ProjectReference Include="..\Mermer.Core.Couch\Mermer.Core.Couch.csproj" />
    <ProjectReference Include="..\Mermer.Http\Mermer.Http.csproj" />
    <ProjectReference Include="..\Mermer\Mermer.Main.csproj" />
    <ProjectReference Include="..\Mermer.Core\Mermer.Core.csproj" />
    <ProjectReference Include="..\Mermer.Mvvm\Mermer.Mvvm.csproj" />
    <ProjectReference Include="..\Mermer.Ui.Core\Mermer.Ui.Core.csproj" />
    <ProjectReference Include="..\Mermer.Ui.Core.Pc\Mermer.Ui.Core.Pc.csproj" />
    <ProjectReference Include="..\Mermer.Licensing.Client\Mermer.Licensing.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DevExpress.Xpf.Themes.Office2013DarkGray.v21.2">
      <HintPath>lib\DevExpress.Xpf.Themes.Office2013DarkGray.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="Splat">
      <HintPath>lib\Splat.dll</HintPath>
    </Reference>
    <Reference Include="Payhas.Binyat">
      <HintPath>lib\Payhas.Binyat.dll</HintPath>
    </Reference>
    <Reference Include="Payhas.Binyat.Core">
      <HintPath>lib\Payhas.Binyat.Core.dll</HintPath>
    </Reference>
    <Reference Include="Payhas.Binyat.Core.Couch">
      <HintPath>lib\Payhas.Binyat.Core.Couch.dll</HintPath>
    </Reference>
    <Reference Include="Payhas.Data.Patcher">
      <HintPath>lib\Payhas.Data.Patcher.dll</HintPath>
    </Reference>
    <Reference Include="Payhas.Data.Synchronizer.Core">
      <HintPath>lib\Payhas.Data.Synchronizer.Core.dll</HintPath>
    </Reference>

    <Reference Include="DevExpress.Data.Desktop.v21.2">
      <HintPath>lib\DevExpress.Data.Desktop.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Data.v21.2">
      <HintPath>lib\DevExpress.Data.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.DataAccess.v21.2">
      <HintPath>lib\DevExpress.DataAccess.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Docs.v21.2">
      <HintPath>lib\DevExpress.Docs.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Mvvm.v21.2">
      <HintPath>lib\DevExpress.Mvvm.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Office.v21.2.Core">
      <HintPath>lib\DevExpress.Office.v21.2.Core.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Printing.v21.2.Core">
      <HintPath>lib\DevExpress.Printing.v21.2.Core.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Spreadsheet.v21.2.Core">
      <HintPath>lib\DevExpress.Spreadsheet.v21.2.Core.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.Controls.v21.2">
      <HintPath>lib\DevExpress.Xpf.Controls.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.Core.v21.2">
      <HintPath>lib\DevExpress.Xpf.Core.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.Grid.v21.2">
      <HintPath>lib\DevExpress.Xpf.Grid.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.Grid.v21.2.Core">
      <HintPath>lib\DevExpress.Xpf.Grid.v21.2.Core.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.LayoutControl.v21.2">
      <HintPath>lib\DevExpress.Xpf.LayoutControl.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.Printing.v21.2">
      <HintPath>lib\DevExpress.Xpf.Printing.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.ReportDesigner.v21.2">
      <HintPath>lib\DevExpress.Xpf.ReportDesigner.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.XtraReports.v21.2">
      <HintPath>lib\DevExpress.XtraReports.v21.2.dll</HintPath>
    </Reference>

    
    <Reference Include="MvvmCross.Core">
      <HintPath>lib\MvvmCross.Core.dll</HintPath>
    </Reference>
    <Reference Include="MvvmCross.Localization">
      <HintPath>lib\MvvmCross.Localization.dll</HintPath>
    </Reference>
    <Reference Include="MvvmCross.Platform">
      <HintPath>lib\MvvmCross.Platform.dll</HintPath>
    </Reference>
    <Reference Include="MvvmCross.Platform.Wpf">
      <HintPath>lib\MvvmCross.Platform.Wpf.dll</HintPath>
    </Reference>
    <Reference Include="MvvmCross.Plugins.Messenger">
      <HintPath>lib\MvvmCross.Plugins.Messenger.dll</HintPath>
    </Reference>
    <Reference Include="MvvmCross.Wpf">
      <HintPath>lib\MvvmCross.Wpf.dll</HintPath>
    </Reference>
    <Reference Include="NuGet.Squirrel">
      <HintPath>lib\NuGet.Squirrel.dll</HintPath>
    </Reference>
    <Reference Include="Squirrel">
      <HintPath>lib\Squirrel.dll</HintPath>
    </Reference>
    <Reference Include="AutoMapper">
      <HintPath>lib\AutoMapper.dll</HintPath>
    </Reference>
    <Reference Include="Autofac.Extras.MvvmCross">
      <HintPath>lib\Autofac.Extras.MvvmCross.dll</HintPath>
    </Reference>

    <Reference Include="System.Printing" />
    <Reference Include="ReachFramework" />

    <Reference Include="DevExpress.Xpf.Themes.Office2016Black.v21.2">
      <HintPath>lib\DevExpress.Xpf.Themes.Office2016Black.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.Themes.HybridApp.v21.2">
      <HintPath>lib\DevExpress.Xpf.Themes.HybridApp.v21.2.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="**\*.png" />
    <Resource Include="**\*.ico" />
    <EmbeddedResource Include="**\*.licenses" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Mermer\Binyat\Ui\Pc\Reports\AggregatedReportAll.resx">
      <LogicalName>Mermer.Ui.Pc.Reports.AggregatedReportAll.resources</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Update="Mermer\Binyat\Ui\Pc\Reports\AggregatedReportFunds.resx">
      <LogicalName>Mermer.Ui.Pc.Reports.AggregatedReportFunds.resources</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Update="Mermer\Binyat\Ui\Pc\Reports\AggregatedReportPartners.resx">
      <LogicalName>Mermer.Ui.Pc.Reports.AggregatedReportPartners.resources</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Update="Mermer\Binyat\Ui\Pc\Reports\AggregatedReportStocks.resx">
      <LogicalName>Mermer.Ui.Pc.Reports.AggregatedReportStocks.resources</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Update="Mermer\Binyat\Ui\Pc\Reports\InvoiceStandard.resx">
      <LogicalName>Mermer.Ui.Pc.Reports.InvoiceStandard.resources</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
    <Folder Include="XamlGeneratedNamespace\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Humanizer" Version="2.14.1" />
    <PackageReference Include="AutoMapper" Version="8.1.1" />
    <PackageReference Include="Castle.Core" Version="4.4.1" />
    <PackageReference Include="CouchbaseNetClient" Version="2.7.27" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="8.0.11" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    <PackageReference Include="System.Management" Version="10.0.8" />
    <PackageReference Include="Autofac" Version="4.9.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="INSTRUCTION.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>